project: 
  type: website

date: last-modified

website: 
  page-navigation: true
  title: "ML4MSD -- Machine Learning for Materials Science and Discovery" 
  site-url: "https://ml4msd.d2r2group.com" 
  repo-url: "https://github.com/d2r2group/ML4MSD"
  repo-actions: [issue]
  google-analytics: "G-C2P3YYMPET"
  favicon: images/favicon.ico
  
  page-footer:
    right: "*Last Update:* {{< meta date >}}"
    left: "&copy; Peter Schindler"
  
  sidebar:
    background: "#B6B8F0"
    logo: images/ML4MSD_logo.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.d2r2group.com
        text: "d2r2group.com"
      - icon: github
        href: https://github.com/d2r2group/ML4MSD
        text: "GitHub Repository"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: content/info.qmd
        text: Information
      - href: content/syllabus.qmd
        text: Outline
      - href: content/grading.qmd
        text: Grading
      - href: content/final_project.qmd
        text: Projects
      - href: content/other.qmd
        text: Guidelines


format:
  html:
    theme:
      dark: [cosmo, theme-dark.scss]
      light: [cosmo, theme.scss]
    template-partials:
      - title-block.html
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true


filters:
  - quarto

  
