---
title: Guidelines, Expectations, and Rights
---

## Attendance

Attendance is an important element for success in class. It is required, unless you are unable to make it due to
illness or other urgent or emergent reasons. Contact me via email before the class time for allowed absence,
unless you are unable to. Here is the section from the student handbook:\

> Students will not be penalized for excused absences, with the understanding that students may need to make up for the
> academic commitment from which they were excused. Reasons for an excused absence include religious, medical issues,
> jury duty, bereavement, and military service. See the course catalog and other applicable policies for the full
> attendance and excusal policy.

## Academic Rights and Responsibilities

For graduate studies, the student bill of academic rights and responsibilities can be
found [here](https://catalog.northeastern.edu/graduate/academic-policies-procedures/students-bill-rights-responsibilities/).
Please, briefly read through it if you haven't done so in the past.

## Academic Integrity

A commitment to the principles of academic integrity is essential to the mission of Northeastern University.
The promotion of independent and original scholarship ensures that students derive the most from their educational
experience and their pursuit of knowledge. Academic dishonesty violates the most fundamental values of an intellectual
community and undermines the achievements of the entire University.\
As members of the academic community, students must become familiar with their rights and responsibilities. In each
course, they are responsible for knowing the requirements and restrictions regarding research and writing, examinations
of whatever kind, collaborative work, the use of study aids, the appropriateness of assistance, and other issues.
Students are responsible for learning the conventions of documentation and acknowledgment of sources in their fields.
Northeastern University expects students to complete all examinations, tests, papers, creative projects, and
assignments of any kind according to the highest ethical standards, as set forth either explicitly or implicitly in
this Code or by the direction of instructors. Go to following link to access the full academic integrity policy:
[osccr.sites.northeastern.edu/academic-integrity-policy/](https://osccr.sites.northeastern.edu/academic-integrity-policy/).<br><br>
Specific **examples of violating academic integrity** in this course are the following (list not exhaustive):

- Copying another student's homework solutions (a reasonable amount of collaboration among students is permitted,
however not direct copying) or from online solutions
- Utilizing/acquiring/sharing homework/exam solutions from previous years
- Cheating during exams
- Not citing sources/figures appropriately when writing the project paper (also, see the next section of utilization of generative AI)

## Utilization of Generative AI

Generative AI tools such as ChatGPT or Bard have become widely adopted and I encourage students to (learn to) use it.
However, similar to using Google to search for information, it is up to the student to decide which output is
trustworthy/correct and which is false ("hallucinated" information). I therefore recommend always taking any output from
generative AI with a healthy amount of scepticism and double-check other sources (and common reasoning) to verify and
tweak the final output. Rarely is it advisable to directly copy-paste information from generative AI and use it as
a final answer.<br>
For final project papers initial generative AI outputs to prompts have to be submitted alongside the final
paper (to assess how effectively you took use of generative AI) - this enables me to grade your critical
thinking skills and development of a subject. Details regarding this policy will be discussed during the semester.

## Student Accommodation

Northeastern University and the Disability Access Services (DAS) are committed to providing disability services that
enable students who qualify under Section 504 of the Rehabilitation Act and the Americans with Disabilities Act
Amendments Act (ADAAA) to participate fully in the activities of the university. To receive accommodations through
the DAS, students must provide appropriate documentation that demonstrates a current substantially limiting disability.
For more information, visit [disabilityaccessservices.northeastern.edu/](https://disabilityaccessservices.northeastern.edu/).

## Diversity and Inclusion

Northeastern University is committed to equal opportunity, affirmative action, diversity and social justice while
building a climate of inclusion on and beyond campus. In the classroom, members of the University community work
to cultivate an inclusive environment that denounces discrimination through innovation, collaboration and an awareness
of global perspectives on social justice. It is my intention that students from all backgrounds and perspectives will
be well served by this course, and that the diversity that students bring to this class will be viewed as an asset.
I welcome individuals of all ages, backgrounds, beliefs, ethnicities, genders, gender identities, gender expressions,
national origins, religious affiliations, sexual orientations, socioeconomic background, family education level,
ability – and other visible and nonvisible differences. All members of this class are expected to contribute to a
respectful, welcoming and inclusive environment for every other member of the class. Your suggestions are encouraged
and appreciated.\
Please visit [belonging.northeastern.edu](https://belonging.northeastern.edu) for complete information on Diversity, Equity,
and Inclusion.

## Title IX

Title IX of the Education Amendments of 1972 protects individuals from sex or gender-based discrimination,
including discrimination based on gender-identity, in educational programs and activities that receive federal
financial assistance. Northeastern’s Title IX Policy prohibits Prohibited Offenses, which are defined as sexual
harassment, sexual assault, relationship or domestic violence, and stalking. The Title IX Policy applies to the
entire community, including male, female, transgender students, faculty and staff. In case of an emergency,
please call NUPD at 617 373 3333. Please visit [ouec.northeastern.edu](https://ouec.northeastern.edu/)
for a complete list of reporting options and resources both on- and off-campus.

